http:
    host: "localhost"
    port: 3333
grpc:
    host: "localhost"
    port: 50051
logger:
    level: "info"
db:
    type: "memory"
    user: "cuser"
    password: ""
    host: "localhost"
    port: 5432
    name: "calendar"
    sslmode: false
