logger:
    level: "info"
db:
    type: "memory"
    user: "cuser"
    password: ""
    host: "localhost"
    port: 5432
    name: "calendar"
    sslmode: false
rmq:
    host: "localhost"
    port: 5672
    user: "user"
    password: ""
    exchangename: "some-name"
    exchangetype: "direct"
    queue: "myQueue"
    bindingkey: "test-binding"
scheduler:
    interval: 10s
    cleanupdays: 365
